spring:
  config:
    import: optional:classpath:.env.localhost[.properties]

  application:
    name: ${SPRING_APP_NAME}
    token-service:
      access-token-exp-ms: ${ACCESS_TOKEN_EXPIRE_MS}
      refresh-token-exp-ms: ${REFRESH_TOKEN_EXPIRE_MS}
      jwt:
        secret: ${TOKEN_SECRET}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=TRUE&characterEncoding=UTF-8&serverTimeZone=UTC&allowPublicKeyRetrieval=TRUE&useSSL=FALSE
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none      # Only Schema Service should be able to update the database schemas
    generate-ddl: false

  cloud:
    config:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH2_SECRET}
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_SECRET}
            scope: read:user, user:email

server:
  port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/"
