spring:
  application:
    name: schema-service
  main:
    web-application-type: none
    banner-mode: off

  datasource:
    url: "jdbc:mysql://mysql:3306/vti_microservices?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC&allowPublicKeyRetrieval=true&useSSL=false"
    username: admin
    password: admin@1234

  jpa:
    hibernate:
      ddl-auto: update      # Only Schema Service should be able to update the database schemas
    generate-ddl: true

  cloud:
    config:
      enabled: false

