spring:
  config:
    import: optional:classpath:.env.localhost[.properties]

  application:
    name: ${SPRING_APP_NAME}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=TRUE&characterEncoding=UTF-8&serverTimeZone=UTC&allowPublicKeyRetrieval=TRUE&useSSL=FALSE
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none      # Only Schema Service should be able to update the database schemas
    generate-ddl: false

  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/

auth-service:
  url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
